version: '2'
services:
  angular:
    image: readmore_angular
    container_name: readmore_angular
    ports:
      - "7000:4200"
      
    volumes:
      - ../ng:/www/ng

    links:
      - api

  api:
    image: readmore_api
    container_name: readmore_api
    volumes:
      - ../api:/www/api

    links: 
      - db

  db:
    image: postgres:10
    container_name: readmore_db
    volumes:
    - ./db.sql:/docker-entrypoint-initdb.d/db.sql

    environment:
      - POSTGRES_DB=readmore
      - POSTGRES_USER=readmore
      - POSTGRES_PASSWORD=R43d3m0r3.#

